apiVersion: apps/v1
kind: Deployment
metadata:
  name: npm-app
  labels:
    app: npm-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: npm-app
  template:
    metadata:
      labels:
        app: npm-app
    spec:
      containers:
        - name: npm-app
          image: :21
          ports:
            - containerPort: 3000
